spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/tasktable
    username: godspride
    password: admin
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      entity-package: com.alex.tasktable.model



